#!/bin/bash

#sndup by Storm Dragon
#License: WTFPL http://wtfpl.net/
#This script makes uploading audio to the http://www.sndup.net/ sound service from both the console and X simple.
#Requires curl and optionally zenity and xclip

shareAdn="FALSE"
shareFacebook="FALSE"
showInfoUrl="true"
shareTwitter="FALSE"

display_info()
{
    if [ "$showInfoUrl" == "true" ] ; then
        message="Information URL: $1\nDownload URL: $2"
    else
        message="$2"
    fi
    if [[ -n $COLORTERM ]] ; then
        result="$(yad --form --title="SndUp URL Information" --selectable-labels --show-uri --field="$message:lbl" --field="Share With App.net:chk" --field="Share With Facebook:chk" --field="Share with Twitter:chk")"
shareAdn="$(echo "$result" | cut -d '|' -f2)"
shareFacebook="$(echo "$result" | cut -d '|' -f3)"
shareTwitter="$(echo "$result" | cut -d '|' -f4)"
        if hash xclip &> /dev/null ; then
            echo -n "$2" | xclip -selection clipboard
        fi
    else
        echo -e "$message"
    fi
if [ "$shareAdn" == "TRUE" -o "$shareFacebook" == "TRUE" -o "$shareTwitter" == "TRUE" ] ; then
post_url $shareAdn $shareFacebook $shareTwitter $2
fi
    exit 0
}

error()
{
    if [[ -n $COLORTERM ]] ; then
        yad --text-info --title="SndUp Error" --text="$1"
    else
        echo -e "Error: $1"
    fi
    exit 1
}

get_file_urls()
{
    filePath="$1"
    upload="$(curl -s --form file="@$filePath" --form submit=upload http://www.sndup.net/post.php)"
    jsonInfo="$(echo "$upload" | sed 's/,/\n/g')"
    fileInfoUrl="$(echo "$jsonInfo" | grep 'url' | sed 's/^{"url":"//' | tr -d '"\\')"
    fileDownloadUrl="$(echo "$fileInfoUrl" | sed 's/a$/d/')"
    errorCode="$(echo "$jsonInfo" | grep '"error":' | tr -Cd "[:digit:]")"
    display_info "$fileInfoUrl" "$fileDownloadUrl" "$errorCode"
}

post_url()
{
    if [[ -n $COLORTERM ]] ; then
postText="$(yad --form --title="SndUp Post RUL" --selectable-labels --field="Enter text to post with your link. Remember App.net has a 256 character limit and Twitter has a 140 character limit.:lbl" --field="$downloadUrl:txt")"
else
read -p "Enter text to post with your link. Remember App.net has a 256 character limit and Twitter has a 140 character limit: " postText
fi
if [ "$1" == "TRUE" ] ; then
texapp -readline=0 -silent -status="$postText $4"
if [ $? -ne 0 ] ; then
postResults="App.net: failed\n"
else
postResults="App.net: succeeded\n"
fi
fi
if [ "$2" == "TRUE" ] ; then
fbcmd post "$postText" 'SndUp | A simple audio sharing service!' "$4"
if [ $? -ne 0 ] ; then
postResults="${postResults}Facebook: failed\n"
else
postResults="${postResults}Facebook: succeeded\n"
fi
fi
if [ "$3" == "TRUE" ] ; then
ttytter -readline=0 -silent -status="$postText $4"
if [ $? -ne 0 ] ; then
postResults="${postResults}Twitter: failed\n"
else
postResults="${postResults}Twitter: succeeded\n"
fi
fi
    if [[ -n $COLORTERM ]] ; then
yad --form --title="SndUp Post URL Results" --selectable-labels --field="Results:$postResults:lbl"
else
echo -e "Results:\n\n$postResults"
fi
}

#If in X and opened with no args, open a file selection dialog with yad
if [ $# -eq 0 ] ; then
    if [[ -n $COLORTERM ]] ; then
    fileName="$(yad --file-selection --title="Select Audio File to Upload to sndup.net")"
        fi
    if [ -n "$fileName" ] ; then
        get_file_urls "$fileName"
    else
        error "No file selected."
    fi
fi

if [ $# -gt 4 ] ; then
    error "Too many arguments. This script requires between 0 and 4 arguments. Optional arguments are:\n-d --download-url: download url only with no other text.\n-f --facebook: Post the url to facebook using fbcmd.\n-i --info-url: Information page with no other text.\nIf you are using X, opened with no arguments, a file selection dialog will be displayed."
fi

while [ $# -gt 1 ] ; do
case "$1" in
"-a"|"--adn")
shareTwitter="true"
;;
"-d"|"--download-url")
        showInfoUrl="false"
;;
"-f"|"--facebook")
shareFacebook="true"
;;
"-t"|"--twitter")
shareTwitter="true"
;;
*)
error "Invalid argument... Valid options are:\n-a --adn: post link to app.net using Texapp.\n-d --download: return download link only, no other text.\n-f --facebook: Post to facebook using fbcmd.\n-t --twitter: Post to twitter using TTYtter."
esac
shift
done

#If file exists, upload it and show the info.
if [ -f "$1" ] ; then
    get_file_urls "$1"
else
    error "No file to uploade."
fi

exit 0
